import { z } from 'zod';

import type { AppConfig } from '../../core/config/types.js';
import type { ISettingMetadata } from '../../core/settings/types.js';

export function createWelcomeSettings(config: Readonly<AppConfig>): ISettingMetadata[] {
  return [
    {
      key: 'welcome.enabled',
      label: 'Welcome Enabled',
      description: 'Enable or disable welcome messages for new members.',
      group: 'general',
      category: 'Welcome',
      type: 'boolean',
      defaultValue: config.bot.welcome.enabled,
      defaultSource: 'config',
      validation: z.boolean(),
      order: 10,
      restartRequired: true,
    },
    {
      key: 'welcome.channelId',
      label: 'Welcome Channel',
      description: 'Text channel where welcome messages are sent.',
      group: 'general',
      category: 'Welcome',
      type: 'channel',
      defaultValue: config.bot.welcome.channelId,
      defaultSource: 'config',
      validation: z.string(),
      order: 20,
      restartRequired: true,
    },
    {
      key: 'welcome.backgroundUrl',
      label: 'Background Image',
      description: 'Image URL used as the welcome card background.',
      group: 'image',
      category: 'Welcome',
      type: 'image',
      defaultValue: config.bot.welcome.backgroundUrl,
      defaultSource: 'config',
      validation: z.string(),
      order: 10,
      restartRequired: true,
    },
    {
      key: 'welcome.message.title',
      label: 'Message Title',
      description: 'Title shown above the welcome message body.',
      group: 'message',
      category: 'Welcome',
      type: 'template',
      defaultValue: config.bot.welcome.message.title,
      defaultSource: 'config',
      validation: z.string(),
      order: 10,
      restartRequired: true,
    },
    {
      key: 'welcome.message.body',
      label: 'Message Body',
      description: 'Welcome message body lines.',
      group: 'message',
      category: 'Welcome',
      type: 'json',
      defaultValue: config.bot.welcome.message.body,
      defaultSource: 'config',
      validation: z.array(z.string()),
      order: 20,
      restartRequired: true,
    },
    {
      key: 'welcome.image.title',
      label: 'Image Title',
      description: 'Large title rendered on the welcome card.',
      group: 'image',
      category: 'Welcome',
      type: 'template',
      defaultValue: config.bot.welcome.image.title,
      defaultSource: 'config',
      validation: z.string(),
      order: 20,
      restartRequired: true,
    },
    {
      key: 'welcome.image.subtitle',
      label: 'Image Subtitle',
      description: 'Subtitle rendered on the welcome card.',
      group: 'image',
      category: 'Welcome',
      type: 'template',
      defaultValue: config.bot.welcome.image.subtitle,
      defaultSource: 'config',
      validation: z.string(),
      order: 30,
      restartRequired: true,
    },
  ];
}
