import { z } from 'zod';

import type { AppConfig } from '../../core/config/types.js';
import type { ISettingMetadata } from '../../core/settings/types.js';

export function createLoggingSettings(config: Readonly<AppConfig>): ISettingMetadata[] {
  return [
    {
      key: 'logging.enabled',
      label: 'Logging Enabled',
      description: 'Enable or disable all logging services.',
      group: 'general',
      category: 'Logging',
      type: 'boolean',
      defaultValue: config.bot.logging.enabled,
      defaultSource: 'config',
      validation: z.boolean(),
      order: 10,
      restartRequired: true,
    },
    {
      key: 'logging.voice.enabled',
      label: 'Voice Logs Enabled',
      description: 'Log voice channel joins, leaves, and moves.',
      group: 'voice',
      category: 'Logging',
      type: 'boolean',
      defaultValue: config.bot.logging.voice.enabled,
      defaultSource: 'config',
      validation: z.boolean(),
      order: 10,
      restartRequired: true,
    },
    {
      key: 'logging.voice.channelId',
      label: 'Voice Log Channel',
      description: 'Text channel where voice activity logs are sent.',
      group: 'voice',
      category: 'Logging',
      type: 'channel',
      defaultValue: config.bot.logging.voice.channelId,
      defaultSource: 'config',
      validation: z.string(),
      order: 20,
      restartRequired: true,
    },
    {
      key: 'logging.member.enabled',
      label: 'Member Logs Enabled',
      description: 'Log member profile and role changes.',
      group: 'member',
      category: 'Logging',
      type: 'boolean',
      defaultValue: config.bot.logging.member.enabled,
      defaultSource: 'config',
      validation: z.boolean(),
      order: 10,
      restartRequired: true,
    },
    {
      key: 'logging.member.channelId',
      label: 'Member Log Channel',
      description: 'Text channel where member activity logs are sent.',
      group: 'member',
      category: 'Logging',
      type: 'channel',
      defaultValue: config.bot.logging.member.channelId,
      defaultSource: 'config',
      validation: z.string(),
      order: 20,
      restartRequired: true,
    },
    {
      key: 'logging.member.roles',
      label: 'Role Change Logs',
      description: 'Log role additions and removals for members.',
      group: 'member',
      category: 'Logging',
      type: 'boolean',
      defaultValue: config.bot.logging.member.roles,
      defaultSource: 'config',
      validation: z.boolean(),
      order: 30,
      restartRequired: true,
    },
    {
      key: 'logging.message.enabled',
      label: 'Message Logs Enabled',
      description: 'Log message deletions, edits, and bulk deletions.',
      group: 'message',
      category: 'Logging',
      type: 'boolean',
      defaultValue: config.bot.logging.message.enabled,
      defaultSource: 'config',
      validation: z.boolean(),
      order: 10,
      restartRequired: true,
    },
    {
      key: 'logging.message.channelId',
      label: 'Message Log Channel',
      description: 'Text channel where message activity logs are sent.',
      group: 'message',
      category: 'Logging',
      type: 'channel',
      defaultValue: config.bot.logging.message.channelId,
      defaultSource: 'config',
      validation: z.string(),
      order: 20,
      restartRequired: true,
    },
    {
      key: 'logging.message.archiveAttachments',
      label: 'Archive Attachments',
      description: 'Attach deleted message files to message deletion logs when possible.',
      group: 'message',
      category: 'Logging',
      type: 'boolean',
      defaultValue: config.bot.logging.message.archiveAttachments,
      defaultSource: 'config',
      validation: z.boolean(),
      order: 30,
      restartRequired: true,
    },
    {
      key: 'logging.message.maxAttachmentSizeMb',
      label: 'Max Attachment Size',
      description: 'Maximum deleted attachment size to archive in message logs.',
      group: 'message',
      category: 'Logging',
      type: 'number',
      defaultValue: config.bot.logging.message.maxAttachmentSizeMb,
      defaultSource: 'config',
      validation: z.number().int().positive(),
      min: 1,
      step: 1,
      unit: 'MB',
      order: 40,
      restartRequired: true,
    },
    {
      key: 'logging.moderation.enabled',
      label: 'Moderation Logs Enabled',
      description: 'Log moderation actions and warnings.',
      group: 'moderation',
      category: 'Logging',
      type: 'boolean',
      defaultValue: config.bot.logging.moderation.enabled,
      defaultSource: 'config',
      validation: z.boolean(),
      order: 10,
      restartRequired: true,
    },
    {
      key: 'logging.moderation.channelId',
      label: 'Moderation Log Channel',
      description: 'Text channel where moderation action logs are sent.',
      group: 'moderation',
      category: 'Logging',
      type: 'channel',
      defaultValue: config.bot.logging.moderation.channelId,
      defaultSource: 'config',
      validation: z.string(),
      order: 20,
      restartRequired: true,
    },
  ];
}
