name: Question
description: Ask a question about the project
title: '[Question]: '
labels: [question]
body:
  - type: markdown
    attributes:
      value: |
        Ask a question about Hoak Bot.
  - type: textarea
    id: question
    attributes:
      label: Question
      description: What would you like to know?
    validations:
      required: true
  - type: textarea
    id: context
    attributes:
      label: Additional context
