import { z } from 'zod';

import type { AppConfig } from '../../core/config/types.js';
import type { ISettingMetadata } from '../../core/settings/types.js';

export function createGeneralSettings(config: Readonly<AppConfig>): ISettingMetadata[] {
  return [
    {
      key: 'general.prefix',
      label: 'Command Prefix',
      description: 'Prefix used for text commands.',
      group: 'commands',
      category: 'General',
      type: 'string',
      defaultValue: config.bot.prefix,
      defaultSource: 'config',
      validation: z.string().min(1).max(20),
      minLength: 1,
      maxLength: 20,
      order: 10,
      restartRequired: true,
    },
    {
      key: 'general.defaultLanguage',
      label: 'Default Language',
      description: 'Default language used by general bot responses.',
      group: 'commands',
      category: 'General',
      type: 'select',
      defaultValue: config.bot.defaultLanguage,
      defaultSource: 'config',
      options: [
        { label: 'English', value: 'en' },
        { label: 'Indonesian', value: 'id' },
      ],
      validation: z.enum(['en', 'id']),
      order: 20,
      restartRequired: true,
    },
    {
      key: 'general.presence.type',
      label: 'Presence Type',
      description: 'Discord presence activity type shown by the bot.',
      group: 'presence',
      category: 'General',
      type: 'select',
      defaultValue: config.bot.presence.type,
      defaultSource: 'config',
      options: [
        { label: 'Playing', value: 'PLAYING' },
        { label: 'Listening', value: 'LISTENING' },
        { label: 'Watching', value: 'WATCHING' },
        { label: 'Competing', value: 'COMPETING' },
      ],
      validation: z.enum(['PLAYING', 'LISTENING', 'WATCHING', 'COMPETING']),
      order: 10,
      restartRequired: true,
    },
    {
      key: 'general.presence.text',
      label: 'Presence Text',
      description: 'Text displayed in the bot presence.',
      group: 'presence',
      category: 'General',
      type: 'string',
      defaultValue: config.bot.presence.text,
      defaultSource: 'config',
      validation: z.string().min(1).max(128),
      minLength: 1,
      maxLength: 128,
      order: 20,
      restartRequired: true,
    },
    {
      key: 'general.cooldowns.global',
      label: 'Global Cooldown',
      description: 'Minimum delay between bot command executions across the guild.',
      group: 'cooldowns',
      category: 'General',
      type: 'number',
      defaultValue: config.bot.cooldowns.global,
      defaultSource: 'config',
      validation: z.number().int().positive(),
      min: 1,
      step: 100,
      unit: 'ms',
      order: 10,
      restartRequired: true,
    },
    {
      key: 'general.cooldowns.perUser',
      label: 'Per User Cooldown',
      description: 'Minimum delay between command executions for one user.',
      group: 'cooldowns',
      category: 'General',
      type: 'number',
      defaultValue: config.bot.cooldowns.perUser,
      defaultSource: 'config',
      validation: z.number().int().positive(),
      min: 1,
      step: 100,
      unit: 'ms',
      order: 20,
      restartRequired: true,
    },
  ];
}
