import { z } from 'zod';

import type { AppConfig } from '../../core/config/types.js';
import type { ISettingMetadata } from '../../core/settings/types.js';

export function createVoiceSettings(config: Readonly<AppConfig>): ISettingMetadata[] {
  return [
    {
      key: 'voice.standbyChannelId',
      label: 'Standby Channel',
      description: 'Voice channel the bot waits in before joining members.',
      group: 'connection',
      category: 'Voice',
      type: 'channel',
      defaultValue: config.bot.voice.standbyChannelId,
      defaultSource: 'config',
      validation: z.string(),
      order: 10,
      restartRequired: true,
    },
    {
      key: 'voice.maxReconnectRetries',
      label: 'Max Reconnect Retries',
      description: 'Maximum reconnection attempts after a voice disconnect.',
      group: 'connection',
      category: 'Voice',
      type: 'number',
      defaultValue: config.bot.voice.maxReconnectRetries,
      defaultSource: 'config',
      validation: z.number().int().positive(),
      min: 1,
      step: 1,
      order: 20,
      restartRequired: true,
    },
    {
      key: 'voice.defaultSound',
      label: 'Default Sound',
      description: 'Sound asset name played when a member joins voice.',
      group: 'playback',
      category: 'Voice',
      type: 'audio',
      defaultValue: config.bot.voice.defaultSound,
      defaultSource: 'config',
      validation: z.string().min(1),
      minLength: 1,
      order: 10,
      restartRequired: true,
    },
    {
      key: 'voice.volume',
      label: 'Volume',
      description: 'Playback volume multiplier for the join sound.',
      group: 'playback',
      category: 'Voice',
      type: 'number',
      defaultValue: config.bot.voice.volume,
      defaultSource: 'config',
      validation: z.number().min(0).max(2),
      min: 0,
      max: 2,
      step: 0.1,
      order: 20,
      restartRequired: true,
    },
    {
      key: 'voice.joinDelayMs',
      label: 'Join Delay',
      description: 'Delay before playing audio after moving to a member channel.',
      group: 'timing',
      category: 'Voice',
      type: 'number',
      defaultValue: config.bot.voice.joinDelayMs,
      defaultSource: 'config',
      validation: z.number().int().min(0),
      min: 0,
      step: 100,
      unit: 'ms',
      order: 10,
      restartRequired: true,
    },
    {
      key: 'voice.cooldownMs',
      label: 'Cooldown',
      description: 'Delay before the voice module can respond to another member join.',
      group: 'timing',
      category: 'Voice',
      type: 'number',
      defaultValue: config.bot.voice.cooldownMs,
      defaultSource: 'config',
      validation: z.number().int().positive(),
      min: 1,
      step: 100,
      unit: 'ms',
      order: 20,
      restartRequired: true,
    },
    {
      key: 'voice.reconnectDelayMs',
      label: 'Reconnect Delay',
      description: 'Base delay before reconnecting to the standby voice channel.',
      group: 'timing',
      category: 'Voice',
      type: 'number',
      defaultValue: config.bot.voice.reconnectDelayMs,
      defaultSource: 'config',
      validation: z.number().int().positive(),
      min: 1,
      step: 100,
      unit: 'ms',
      order: 30,
      restartRequired: true,
    },
  ];
}
