import { EventEmitter } from 'node:events';
import { vi } from 'vitest';

export const ids = Object.freeze({ guild: '100000000000000001', member: '100000000000000002', channel: '100000000000000003', user: '100000000000000004' });
export const fixture = <T extends object>(defaults: T, overrides: Partial<T> = {}): T => Object.freeze({ ...defaults, ...overrides });
export const discordUser = (overrides = {}) => fixture({ id: ids.user, username: 'fixture-user', bot: false, displayAvatarURL: vi.fn(() => 'https://cdn.discordapp.com/embed/avatars/0.png') }, overrides);
export const guild = (overrides = {}) => fixture({ id: ids.guild, name: 'Fixture Guild', ownerId: ids.user, memberCount: 2, channels: { cache: new Map() }, members: { cache: new Map() } }, overrides);
export const member = (overrides = {}) => fixture({ id: ids.member, user: discordUser(), guild: guild(), permissions: { has: vi.fn(() => true) }, roles: { cache: new Map() } }, overrides);
export const channel = (overrides = {}) => fixture({ id: ids.channel, guildId: ids.guild, name: 'fixture-channel', isTextBased: vi.fn(() => true), send: vi.fn() }, overrides);
export const interaction = (overrides = {}) => fixture({ id: 'interaction-1', guildId: ids.guild, guild: guild(), member: member(), channel: channel(), user: discordUser(), commandName: 'fixture', replied: false, deferred: false, isChatInputCommand: vi.fn(() => true), isAutocomplete: vi.fn(() => false), isButton: vi.fn(() => false), isStringSelectMenu: vi.fn(() => false), reply: vi.fn(), deferReply: vi.fn(), editReply: vi.fn(), respond: vi.fn(), options: { getString: vi.fn(), getUser: vi.fn(), getInteger: vi.fn() } }, overrides);
export const logger = () => ({ trace: vi.fn(), debug: vi.fn(), info: vi.fn(), warn: vi.fn(), error: vi.fn(), fatal: vi.fn(), child: vi.fn() });
export const database = () => ({ query: vi.fn(), transaction: vi.fn(async (run: (value: unknown) => unknown) => run({ query: vi.fn() })) });
export const cache = () => { const values = new Map<string, unknown>(); return { values, get: vi.fn((key: string) => values.get(key)), set: vi.fn((key: string, value: unknown) => values.set(key, value)), delete: vi.fn((key: string) => values.delete(key)), clear: vi.fn(() => values.clear()) }; };
export const configuration = <T extends object>(value: T) => { let current = structuredClone(value); return { current: vi.fn(() => structuredClone(current)), update: vi.fn((next: Partial<T>) => { current = { ...current, ...next }; return structuredClone(current); }) }; };
export const eventBus = () => { const emitter = new EventEmitter(); return { emit: vi.fn((name: string, ...args: unknown[]) => emitter.emit(name, ...args)), publish: vi.fn((event: { type: string }) => emitter.emit(event.type, event)), subscribe: vi.fn((name: string, handler: (...args: unknown[]) => void) => { emitter.on(name, handler); return () => emitter.off(name, handler); }), listenerCount: (name: string) => emitter.listenerCount(name) }; };
export const registry = () => { const handlers = new Map<string, (...args: unknown[]) => unknown>(); return { handlers, register: vi.fn((name: string, handler: (...args: unknown[]) => unknown) => handlers.set(name, handler)), unregister: vi.fn((name: string) => handlers.delete(name)), invoke: (name: string, ...args: unknown[]) => handlers.get(name)?.(...args) }; };
export const assets = () => { const values = new Map<string, Uint8Array>(); return { values, put: (name: string, value: Uint8Array) => values.set(name, value), read: vi.fn((name: string) => { const value = values.get(name); if (!value) throw new Error(`Missing asset: ${name}`); return value; }), corrupt: (name: string) => values.set(name, new Uint8Array([0xff, 0x00])) }; };
export const failures = () => ({ next: undefined as Error | undefined, inject(error: Error) { this.next = error; }, consume() { const error = this.next; this.next = undefined; if (error) throw error; } });
export const fakeClock = () => ({ install: () => vi.useFakeTimers(), set: (date: Date | number | string) => vi.setSystemTime(date), advance: (milliseconds: number) => vi.advanceTimersByTimeAsync(milliseconds), pending: () => vi.getTimerCount(), restore: () => vi.useRealTimers() });
