import { z } from 'zod';

import type { AppConfig } from '../../core/config/types.js';
import type { ISettingMetadata } from '../../core/settings/types.js';

export function createShrineSettings(config: Readonly<AppConfig>): ISettingMetadata[] {
  return [
    {
      key: 'shrine.enabled',
      label: 'Shrine Enabled',
      description: 'Enable or disable Shrine of Secrets announcements.',
      group: 'general',
      category: 'Shrine of Secrets',
      type: 'boolean',
      defaultValue: config.bot.shrine.enabled,
      defaultSource: 'config',
      validation: z.boolean(),
      order: 10,
      restartRequired: true,
    },
    {
      key: 'shrine.guildId',
      label: 'Shrine Guild',
      description: 'Guild ID to announce Shrine rotations in. Defaults to the bot guild ID when empty.',
      group: 'general',
      category: 'Shrine of Secrets',
      type: 'text',
      defaultValue: config.bot.shrine.guildId,
      defaultSource: 'config',
      validation: z.string(),
      order: 20,
      restartRequired: true,
    },
    {
      key: 'shrine.channelId',
      label: 'Shrine Channel',
      description: 'Text channel where Shrine announcements are sent.',
      group: 'general',
      category: 'Shrine of Secrets',
      type: 'channel',
      defaultValue: config.bot.shrine.channelId,
      defaultSource: 'config',
      validation: z.string(),
      order: 30,
      restartRequired: true,
    },
    {
      key: 'shrine.nightLightBaseUrl',
      label: 'NightLight API Base URL',
      description: 'Base URL for the NightLight API.',
      group: 'api',
      category: 'Shrine of Secrets',
      type: 'text',
      defaultValue: config.bot.shrine.nightLightBaseUrl,
      defaultSource: 'config',
      validation: z.string().url(),
      order: 10,
      restartRequired: true,
    },
    {
      key: 'shrine.imageCdnUrl',
      label: 'Image CDN URL',
      description: 'Base URL for reusable NightLight image assets.',
      group: 'api',
      category: 'Shrine of Secrets',
      type: 'text',
      defaultValue: config.bot.shrine.imageCdnUrl,
      defaultSource: 'config',
      validation: z.string().url(),
      order: 20,
      restartRequired: true,
    },
    {
      key: 'shrine.portraitFolder',
      label: 'Portrait Folder',
      description: 'Folder beneath the image CDN containing character portraits.',
      group: 'api',
      category: 'Shrine of Secrets',
      type: 'text',
      defaultValue: config.bot.shrine.portraitFolder,
      defaultSource: 'config',
      validation: z.string().trim().min(1),
      order: 30,
      restartRequired: false,
    },
    {
      key: 'shrine.perkFolder',
      label: 'Perk Folder',
      description: 'Folder beneath the image CDN containing perk icons.',
      group: 'api',
      category: 'Shrine of Secrets',
      type: 'text',
      defaultValue: config.bot.shrine.perkFolder,
      defaultSource: 'config',
      validation: z.string().trim().min(1),
      order: 40,
      restartRequired: false,
    },
    {
      key: 'shrine.iridescentShardIcon',
      label: 'Iridescent Shard Icon Path',
      description: 'Image path beneath the image CDN for the Iridescent Shard icon.',
      group: 'api',
      category: 'Shrine of Secrets',
      type: 'text',
      defaultValue: config.bot.shrine.iridescentShardIcon,
      defaultSource: 'config',
      validation: z.string().trim().min(1),
      order: 50,
      restartRequired: false,
    },
    {
      key: 'shrine.polling.pollIntervalMs',
      label: 'Poll Interval',
      description: 'Polling interval near reset in milliseconds.',
      group: 'polling',
      category: 'Shrine of Secrets',
      type: 'number',
      defaultValue: config.bot.shrine.polling.pollIntervalMs,
      defaultSource: 'config',
      validation: z.number().int().positive(),
      order: 10,
      restartRequired: true,
    },
    {
      key: 'shrine.polling.preResetWindowMs',
      label: 'Pre-reset Window',
      description: 'How long before the API reset time to start polling aggressively.',
      group: 'polling',
      category: 'Shrine of Secrets',
      type: 'number',
      defaultValue: config.bot.shrine.polling.preResetWindowMs,
      defaultSource: 'config',
      validation: z.number().int().positive(),
      order: 20,
      restartRequired: true,
    },
    {
      key: 'shrine.polling.delayedUpdateWindowMs',
      label: 'Delayed Update Window',
      description: 'How long to keep fast polling after reset if NightLight has not updated yet.',
      group: 'polling',
      category: 'Shrine of Secrets',
      type: 'number',
      defaultValue: config.bot.shrine.polling.delayedUpdateWindowMs,
      defaultSource: 'config',
      validation: z.number().int().positive(),
      order: 30,
      restartRequired: true,
    },
    {
      key: 'shrine.polling.fallbackRetryMs',
      label: 'Fallback Retry',
      description: 'Lower-frequency retry interval after the delayed update window.',
      group: 'polling',
      category: 'Shrine of Secrets',
      type: 'number',
      defaultValue: config.bot.shrine.polling.fallbackRetryMs,
      defaultSource: 'config',
      validation: z.number().int().positive(),
      order: 40,
      restartRequired: true,
    },
    {
      key: 'shrine.dev.forceAnnouncementOnStartup',
      label: 'Force Startup Announcement',
      description: 'Development-only option to send the current Shrine announcement immediately after startup synchronization.',
      group: 'dev',
      category: 'Shrine of Secrets',
      type: 'boolean',
      defaultValue: config.bot.shrine.dev.forceAnnouncementOnStartup,
      defaultSource: 'config',
      validation: z.boolean(),
      order: 10,
      restartRequired: true,
      advanced: true,
    },
  ];
}
