export interface EventInventoryEntry { readonly id: string; readonly owner: string; readonly source: 'internal' | 'discord' | 'configuration'; readonly status: 'active' | 'dormant'; readonly publishes: readonly string[]; readonly subscribes: readonly string[]; readonly dependencies: readonly string[]; readonly priority: number; readonly aliases: readonly string[] }
const event = (entry: Omit<EventInventoryEntry, 'status' | 'publishes' | 'subscribes' | 'dependencies' | 'priority'> & Partial<Pick<EventInventoryEntry, 'status' | 'publishes' | 'subscribes' | 'dependencies' | 'priority'>>): EventInventoryEntry => Object.freeze({ status: 'active', publishes: [entry.owner], subscribes: [], dependencies: [], priority: 0, ...entry });
export const eventCatalogInventory = Object.freeze([
  event({ id: 'bot.ready', owner: 'core.system', source: 'internal', aliases: [] }),
  event({ id: 'bot.error', owner: 'core.system', source: 'internal', aliases: [] }),
  event({ id: 'system.shutdown', owner: 'core.system', source: 'internal', aliases: [] }),
  event({ id: 'configuration.changed', owner: 'core.configuration', source: 'configuration', aliases: [] }),
  event({ id: 'command.executed', owner: 'builtin.general', source: 'internal', aliases: [] }),
  event({ id: 'command.failed', owner: 'builtin.general', source: 'internal', aliases: [] }),
  event({ id: 'cooldown.blocked', owner: 'builtin.general', source: 'internal', aliases: [] }),
  event({ id: 'permission.denied', owner: 'builtin.general', source: 'internal', aliases: [] }),
  event({ id: 'scheduler.jobDue', owner: 'builtin.general', source: 'internal', aliases: ['scheduler.job_due'], status: 'dormant' }),
  event({ id: 'member.joined', owner: 'builtin.welcome', source: 'discord', aliases: [] }),
  event({ id: 'member.left', owner: 'builtin.goodbye', source: 'discord', aliases: [] }),
  event({ id: 'moderation.action', owner: 'builtin.moderation', source: 'internal', aliases: [] }),
  event({ id: 'moderation.warningIssued', owner: 'builtin.moderation', source: 'internal', aliases: ['moderation.warning_issued'], subscribes: ['builtin.logging'], priority: 100 }),
  event({ id: 'shrine.updated', owner: 'builtin.shrine', source: 'internal', aliases: [] }),
  event({ id: 'shrine.poll_failed', owner: 'builtin.shrine', source: 'internal', aliases: [] }),
  event({ id: 'voice.memberJoined', owner: 'builtin.voice', source: 'discord', aliases: ['voice.member_joined'], subscribes: ['builtin.voice'], priority: 100 }),
  event({ id: 'voice.soundPlayed', owner: 'builtin.voice', source: 'internal', aliases: ['voice.sound_played'], status: 'dormant' }),
  event({ id: 'voice.connectionLost', owner: 'builtin.voice', source: 'internal', aliases: ['voice.connection_lost'], status: 'dormant' }),
  event({ id: 'voice.connectionRestored', owner: 'builtin.voice', source: 'internal', aliases: ['voice.connection_restored'], status: 'dormant' }),
  event({ id: 'logging.member.nickname_updated', owner: 'builtin.logging', source: 'discord', aliases: [] }),
  event({ id: 'logging.member.role_added', owner: 'builtin.logging', source: 'discord', aliases: [] }),
  event({ id: 'logging.member.role_removed', owner: 'builtin.logging', source: 'discord', aliases: [] }),
  event({ id: 'logging.member.display_name_updated', owner: 'builtin.logging', source: 'discord', aliases: [] }),
  event({ id: 'logging.member.avatar_updated', owner: 'builtin.logging', source: 'discord', aliases: [] }),
  event({ id: 'logging.message.deleted', owner: 'builtin.logging', source: 'discord', aliases: [] }),
  event({ id: 'logging.message.edited', owner: 'builtin.logging', source: 'discord', aliases: [] }),
  event({ id: 'logging.message.bulk_deleted', owner: 'builtin.logging', source: 'discord', aliases: [] }),
  event({ id: 'logging.message.attachments_archived', owner: 'builtin.logging', source: 'internal', aliases: [] }),
  event({ id: 'logging.moderation.kick_logged', owner: 'builtin.logging', source: 'internal', aliases: [] }),
  event({ id: 'logging.moderation.logged', owner: 'builtin.logging', source: 'internal', aliases: [] }),
] as const);
