import type { DashboardUser, GuildSummary, ModuleManifest, SettingMetadata } from '../contracts.js';

export const mockUser: DashboardUser = {
  id: 'demo-user',
  username: 'Demo Admin',
};

export const mockGuilds: GuildSummary[] = [
  { id: 'guild-alpha', name: 'Alpha Guild' },
  { id: 'guild-beta', name: 'Beta Guild' },
];

export const mockManifests: ModuleManifest[] = [
  {
    id: 'general',
    name: 'General',
    description: 'General command behavior and bot presentation settings.',
    icon: 'Bot',
    color: '#2563eb',
    category: 'utility',
    version: '1.0.0',
    author: 'Hoak',
    settings: [
      'general.prefix',
      'general.defaultLanguage',
      'general.presence.type',
      'general.presence.text',
      'general.cooldowns.global',
      'general.cooldowns.perUser',
    ],
    commands: ['ping', 'help', 'avatar', 'userinfo', 'serverinfo', 'botinfo'],
    events: ['interactionCreate', 'messageCreate'],
    routes: ['/modules/general/settings', '/guilds/:guildId/settings'],
    dashboard: {
      navigation: { sidebarPriority: 10, sidebarSection: 'Utility' },
      homePage: { featured: true, priority: 10 },
      settings: {
        groups: [
          { key: 'commands', label: 'Commands', order: 10 },
          { key: 'presence', label: 'Presence', order: 20 },
          { key: 'cooldowns', label: 'Cooldowns', order: 30 },
        ],
      },
    },
    supportsHotReload: false,
  },
  {
    id: 'module:automation',
    name: 'Automation',
    description: 'Automated workflows and scheduled actions.',
    icon: 'Workflow',
    color: '#2563eb',
    category: 'automation',
    version: '1.0.0',
    author: 'Hoak',
    dashboard: {
      navigation: { sidebarPriority: 20, sidebarSection: 'Operations' },
      homePage: { featured: true, priority: 10 },
      settings: { groups: [{ key: 'general', label: 'General' }] },
    },
    supportsHotReload: true,
  },
  {
    id: 'module:community',
    name: 'Community',
    description: 'Member experience and community utilities.',
    icon: 'Users',
    color: '#059669',
    category: 'engagement',
    version: '1.0.0',
    author: 'Hoak',
    dashboard: {
      navigation: { sidebarPriority: 10, sidebarSection: 'Community' },
      homePage: { featured: true, priority: 5 },
      settings: { groups: [{ key: 'general', label: 'General' }] },
    },
    supportsHotReload: false,
  },
];

export const mockSettings: SettingMetadata[] = [
  {
    key: 'general.prefix',
    label: 'Command Prefix',
    description: 'Prefix used for text commands.',
    group: 'commands',
    category: 'General',
    type: 'string',
    defaultValue: 'hoak',
    minLength: 1,
    maxLength: 20,
    restartRequired: true,
  },
  {
    key: 'general.defaultLanguage',
    label: 'Default Language',
    description: 'Default language used by general bot responses.',
    group: 'commands',
    category: 'General',
    type: 'select',
    defaultValue: 'en',
    options: [
      { label: 'English', value: 'en' },
      { label: 'Indonesian', value: 'id' },
    ],
    restartRequired: true,
  },
  {
    key: 'general.presence.type',
    label: 'Presence Type',
    description: 'Discord presence activity type shown by the bot.',
    group: 'presence',
    category: 'General',
    type: 'select',
    defaultValue: 'WATCHING',
    options: [
      { label: 'Playing', value: 'PLAYING' },
      { label: 'Listening', value: 'LISTENING' },
      { label: 'Watching', value: 'WATCHING' },
      { label: 'Competing', value: 'COMPETING' },
    ],
    restartRequired: true,
  },
  {
    key: 'general.presence.text',
    label: 'Presence Text',
    description: 'Text displayed in the bot presence.',
    group: 'presence',
    category: 'General',
    type: 'string',
    defaultValue: 'the Hoak Family',
    minLength: 1,
    maxLength: 128,
    restartRequired: true,
  },
  {
    key: 'general.cooldowns.global',
    label: 'Global Cooldown',
    description: 'Minimum delay between bot command executions across the guild.',
    group: 'cooldowns',
    category: 'General',
    type: 'number',
    defaultValue: 1000,
    min: 1,
    step: 100,
    unit: 'ms',
    restartRequired: true,
  },
  {
    key: 'general.cooldowns.perUser',
    label: 'Per User Cooldown',
    description: 'Minimum delay between command executions for one user.',
    group: 'cooldowns',
    category: 'General',
    type: 'number',
    defaultValue: 3000,
    min: 1,
    step: 100,
    unit: 'ms',
    restartRequired: true,
  },
];
