#!/usr/bin/env node
import { spawn } from 'node:child_process';
import { createHash } from 'node:crypto';
import { readFile, rm } from 'node:fs/promises';
import { dirname, join, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';
import { createPlugin } from './cli/create.js'; import { inventory, redact } from './cli/inspect.js'; import { readStaticManifest, validateCatalog } from './cli/validation.js';
const raw = process.argv.slice(2); const command = raw.shift(); const json = raw.includes('--json'); const option = (name: string): string | undefined => { const index = raw.indexOf(name); return index >= 0 ? raw[index + 1] : undefined; }; const values = raw.filter((value, index) => value !== '--json' && !value.startsWith('--') && !raw[index - 1]?.startsWith('--'));
const emit = (payload: unknown): void => { process.stdout.write(`${json ? JSON.stringify(payload) : JSON.stringify(payload, null, 2)}\n`); };
const fail = (code: string, message: string, exitCode = 1): never => { const payload = { ok: false, diagnostics: [{ code, message }] }; if (json) emit(payload); else process.stderr.write(`${code}: ${message}\n`); process.exit(exitCode); };
const run = (stage: string, cwd: string, timeoutMs = 120000): Promise<{ stage: string; durationMs: number }> => new Promise((accept, reject) => { const started = Date.now(); const child = spawn('npm', ['run', stage], { cwd, shell: false, stdio: json ? ['ignore', 'pipe', 'pipe'] : 'inherit', detached: process.platform !== 'win32' }); let stderr = ''; if (child.stderr) child.stderr.on('data', (chunk) => stderr += String(chunk)); const timer = setTimeout(() => { if (child.pid && process.platform !== 'win32') process.kill(-child.pid, 'SIGTERM'); else child.kill('SIGTERM'); const killTimer = setTimeout(() => child.kill('SIGKILL'), 2000); killTimer.unref(); reject(new Error(`PREFLIGHT_TIMEOUT:${stage}`)); }, timeoutMs); timer.unref(); child.on('error', reject); child.on('exit', (code) => { clearTimeout(timer); if (code === 0) accept({ stage, durationMs: Date.now() - started }); else reject(new Error(`STAGE_FAILED:${stage}:${code}:${stderr.trim()}`)); }); });
const checkPackage = async (cwd: string) => { const pkg = JSON.parse(await readFile(join(cwd, 'package.json'), 'utf8')); if (pkg.type !== 'module' || !pkg.exports || !pkg.bin || !pkg.files) fail('INVALID_PACKAGE', 'Package must define ESM exports, bin, and files'); const files = await inventory(cwd); const paths = new Set(files.map((file) => file.path)); const manifest = await readStaticManifest(join(cwd, 'hoakbot.plugin.json')); if (!manifest.ok) fail(manifest.diagnostics[0]?.code ?? 'INVALID_MANIFEST', manifest.diagnostics[0]?.message ?? 'Invalid manifest'); const assets = (manifest.manifest as any).contracts?.assets?.map((item: any) => item.path) ?? []; for (const asset of assets) if (!paths.has(asset)) fail('MISSING_ASSET', asset); const targets: string[] = []; const collect = (value: unknown): void => { if (typeof value === 'string' && value.startsWith('./')) targets.push(value.slice(2)); else if (value && typeof value === 'object') for (const item of Object.values(value)) collect(item); }; collect(pkg.exports); collect(pkg.bin); for (const target of targets) if (!paths.has(target)) fail('MISSING_EXPORT', target); return { pkg, assets, files }; };
try {
 if (command === 'create') { const candidate = values[0]; if (!candidate) fail('USAGE', 'create requires <name> [directory]', 2); const name = candidate as string; const directory = values[1] ?? name; await createPlugin(name, directory, resolve(dirname(fileURLToPath(import.meta.url)), '../templates/plugin-v1'), { id: option('--id'), description: option('--description'), license: option('--license') }); emit({ ok: true, path: resolve(directory) }); }
 else if (command === 'validate') { if (!values.length) fail('USAGE', 'validate requires manifest paths', 2); const results = await Promise.all(values.map(readStaticManifest)); const diagnostics = [...results.flatMap((item) => item.diagnostics), ...validateCatalog(results.flatMap((item) => item.manifest ? [item.manifest] : []))]; emit({ ok: !diagnostics.length, diagnostics }); if (diagnostics.length) process.exitCode = 1; }
 else if (command === 'inspect') { const result = await readStaticManifest(values[0] ?? 'hoakbot.plugin.json'); if (!result.ok) fail(result.diagnostics[0]?.code ?? 'INVALID_MANIFEST', result.diagnostics[0]?.message ?? 'Invalid manifest'); emit({ ok: true, manifest: redact(result.manifest) }); }
 else if (command === 'preflight') { const cwd = resolve(values[0] ?? '.'); const pkg = JSON.parse(await readFile(join(cwd, 'package.json'), 'utf8')); for (const stage of ['typecheck', 'test', 'build']) if (!pkg.scripts?.[stage]) fail('MISSING_SCRIPT', stage); const stages = []; for (const stage of ['typecheck', 'test', 'build']) stages.push(await run(stage, cwd, Number(option('--timeout-ms') ?? 120000))); emit({ ok: true, stages }); }
 else if (command === 'check') { const checked = await checkPackage(resolve(values[0] ?? '.')); emit({ ok: true, exports: checked.pkg.exports, assets: checked.assets, inventory: checked.files }); }
 else if (command === 'pack') { const cwd = resolve(values[0] ?? '.'); await checkPackage(cwd); const result = await new Promise<string>((accept, reject) => { const child = spawn('npm', ['pack', '--ignore-scripts', '--json'], { cwd, shell: false, stdio: ['ignore', 'pipe', 'pipe'] }); let out = '', err = ''; child.stdout.on('data', (chunk) => out += String(chunk)); child.stderr.on('data', (chunk) => err += String(chunk)); child.on('exit', (code) => code === 0 ? accept(out) : reject(new Error(err))); }); const packed = JSON.parse(result)[0]; for (const file of packed.files) { if (file.path.includes('..') || file.path.startsWith('/') || /(?:^|\/)(?:\.env|node_modules|\.git)(?:\/|$)/.test(file.path)) fail('UNSAFE_PACK_ENTRY', file.path); } const tarball = await readFile(join(cwd, packed.filename)); const integrity = `sha512-${createHash('sha512').update(tarball).digest('base64')}`; if (integrity !== packed.integrity) fail('INTEGRITY_MISMATCH', packed.filename); emit({ ok: true, pack: packed }); if (option('--cleanup') === 'true') await rm(join(cwd, packed.filename)); }
 else fail('USAGE', 'Usage: hoak-plugin <create|validate|inspect|preflight|check|pack>', 2);
} catch (error) { fail('COMMAND_FAILED', error instanceof Error ? error.message : String(error)); }
