import { readFile } from 'node:fs/promises';
import { resolve } from 'node:path';
import type { PluginManifest } from '../contracts.js';
import { pluginManifestSchema } from '../manifest-schema.js';
export interface Diagnostic { readonly code: string; readonly message: string; readonly path?: readonly (string | number)[] }
export interface Validation { readonly ok: boolean; readonly manifest?: PluginManifest; readonly diagnostics: readonly Diagnostic[] }
export async function readStaticManifest(path: string): Promise<Validation> { try { const value: unknown = JSON.parse(await readFile(resolve(path), 'utf8')); const parsed = pluginManifestSchema.safeParse(value); if (parsed.success) return { ok: true, manifest: parsed.data, diagnostics: [] }; return { ok: false, diagnostics: parsed.error.issues.map((issue) => ({ code: 'INVALID_MANIFEST', message: issue.message, path: issue.path })) }; } catch (error) { return { ok: false, diagnostics: [{ code: 'MANIFEST_READ_ERROR', message: error instanceof Error ? error.message : String(error) }] }; } }
const parseVersion = (value: string): [number, number, number] | undefined => { const match = /^(\d+)\.(\d+)\.(\d+)/.exec(value); return match ? [Number(match[1]), Number(match[2]), Number(match[3])] : undefined; };
const satisfies = (version: string, range: string): boolean => { if (range === '*') return true; const actual = parseVersion(version); const requested = parseVersion(range.replace(/^[~^]/, '')); if (!actual || !requested) return false; if (range.startsWith('^')) return actual[0] === requested[0] && (actual[1] > requested[1] || actual[1] === requested[1] && actual[2] >= requested[2]); if (range.startsWith('~')) return actual[0] === requested[0] && actual[1] === requested[1] && actual[2] >= requested[2]; return actual.every((part, index) => part === requested[index]); };
function exclusiveCapabilities(manifest: PluginManifest): ReadonlyMap<string, readonly string[]> { const ownership = manifest.capabilities.ownership; const hasRouteOwnership = ownership.routes.owners.length > 0 || ownership.routes.contributors.length > 0; const hasEventOwnership = ownership.events.publishers.length > 0 || ownership.events.subscribers.length > 0; return new Map<string, readonly string[]>([['settings', manifest.capabilities.settings], ['commands', ownership.commands.length ? ownership.commands : manifest.capabilities.commands], ['permissions', manifest.capabilities.permissions], ['routes', hasRouteOwnership ? ownership.routes.owners : manifest.capabilities.routes], ['events', hasEventOwnership ? ownership.events.publishers : manifest.capabilities.events], ['schedulers', ownership.schedulers], ['assets', ownership.assets]]); }
export function validateCatalog(manifests: readonly PluginManifest[]): Diagnostic[] { const diagnostics: Diagnostic[] = []; const byId = new Map<string, PluginManifest>(); const capabilities = new Map<string, string>(); for (const manifest of manifests) { if (byId.has(manifest.id)) diagnostics.push({ code: 'DUPLICATE_PLUGIN_ID', message: `Duplicate plugin id: ${manifest.id}` }); else byId.set(manifest.id, manifest); for (const [kind, values] of exclusiveCapabilities(manifest)) for (const value of values) { const key = `${kind}:${value}`; const owner = capabilities.get(key); if (owner && owner !== manifest.id) diagnostics.push({ code: 'CAPABILITY_COLLISION', message: `${key} is declared by ${owner} and ${manifest.id}` }); else capabilities.set(key, manifest.id); } }
  for (const manifest of manifests) for (const dependency of manifest.dependencies ?? []) { if (dependency.id === manifest.id) diagnostics.push({ code: 'SELF_DEPENDENCY', message: `${manifest.id} depends on itself` }); const target = byId.get(dependency.id); if (!target) diagnostics.push({ code: 'MISSING_DEPENDENCY', message: `${manifest.id} requires ${dependency.id}` }); else if (!satisfies(target.version, dependency.range)) diagnostics.push({ code: 'DEPENDENCY_RANGE_MISMATCH', message: `${manifest.id} requires ${dependency.id}@${dependency.range}, found ${target.version}` }); }
  const visiting = new Set<string>(); const visited = new Set<string>(); const visit = (id: string): void => { if (visiting.has(id)) { diagnostics.push({ code: 'DEPENDENCY_CYCLE', message: `Dependency cycle includes ${id}` }); return; } if (visited.has(id)) return; visiting.add(id); for (const dep of byId.get(id)?.dependencies ?? []) if (byId.has(dep.id)) visit(dep.id); visiting.delete(id); visited.add(id); }; for (const id of byId.keys()) visit(id); return diagnostics; }
